### ISSUE TITLE
Getting error Error: ENOENT: no such file or directory, open 

### ISSUE THREAD

**Issue by aditya-kanekar-bo** [facebookincubator/offline-conversion-file-uploader#20]
I am trying to execute the sample from the guide. I followed all the instructions setting up environment variables for accessToken and data_set_id. I provided the test json file as described in the guide. After running below command,

node lib\cli.js upload --configFilePath offline-events\demo-offline-events\config-test-upload.json --inputFilePath offline-events\demo-offline-events\test-event-files\test-events-2019-06-24T135313.357Z.csv --accessToken %access_token% --dataSetID %data_set_id%--apiVersion v3.3

I am getting error,

Using option accessToken:  '<token>'
Using option batchSize:  2000
Using option customTypeInfo:  {}
Using option dataSetID:  '<data_set_id>'
Using option delimiter:  ,
Using option format:  {
  "event_time": {
    "timeFormat": "unix_time"
  }
}
Using option header:  false
Using option inputFilePath:  offline-events\demo-offline-events\test-event-files\test-events-2019-06-24T135313.357Z.csv
Using option logging:  verbose
Using option mapping:  {
  "0": "match_keys.email",
  "1": "match_keys.phone",
  "2": "event_time",
  "3": "event_name",
  "4": "value",
  "5": "currency"
}
Using option presetValues:  {}
Using option reportOutputPath:  report.txt
Option uploadTag, uploadTagPrefix and uploadID is deprecated. Please make sure that your file name contains date stamp, and leave the parameters unset. An uploadTag will be generated automaticially based on the name and size of input file. With skipRowsAlreadyUploaded option, the uploader can upload reliably and make sure each row is uploaded once and only once.
Using option uploadTagPrefix:  Legacy upload tag prefix
Using option apiVersion:  v3.3
2019-06-24T14:07:52.968Z INFO Config and logger initialized.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '~\offline-conversion-file-uploader\upload-test-events-2019-06-24T135313.357Z.csv-2019-06-24T14:07:52.956Z-txt.log'
Emitted 'error' event at:
    at WriteStream.<anonymous> (~\offline-conversion-file-uploader\node_modules\winston\lib\winston\transports\file.js:491:16)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by rayice** [comment]
No body here to response on this bug ?

**Comment by aditya-kanekar-bo** [comment]
I figured it out, when I try to run the code on Windows environment I get this error, however it works just fine in Linux environment.

**Comment by prabhu-pandian** [comment]
Hi guys.. I am currently facing the same error running from Windows. Are there any fixes apart from running on Linux ?
